### ISSUE TITLE
Make a readme!

### ISSUE THREAD

**Issue by 3vivekb** [vta/Data-Gathering#2]
Describe the project and its goals.

**Comment by SJClaus** [comment]
Done

**Comment by SJClaus** [comment]
Done

**Comment by SJClaus** [comment]
Done

**Comment by 3vivekb** [comment]
What you created isn't really a Readme but something else.  Somebody should create a proper readme with nice markdown.    Here is a list of awesome descriptive readmes.
https://github.com/matiassingers/awesome-readme

**Comment by Kyle-Falconer** [comment]
It doesn't need to be as fancy as some of those listed, but it should have the name of `readme.md` so that GitHub picks it up properly. It should also be descriptive and well-structured so that someone coming across the repository can, at a glance, see what the project is for, and at a closer read, find out as much information as is required to use what's in the repository.

**Comment by SJClaus** [comment]
Readme is done.
